spring.application.name=patient_service


spring.datasource.url=jdbc:postgresql://localhost:5432/patient
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
logging.level.com.assignment.patient.api=DEBUG

# Optional: Save logs to a file
logging.file.name=logs/patient_assignment.log