package com.assignment.patient.api.controller;

import org.springframework.http.*;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.context.request.WebRequest;
import org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler;

import java.net.URI;
import java.time.Instant;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * The GenericExceptionHandler - generic and global exception handler that handle all the response errors
 * and validation errors and return the error response with standard common format
 */
@RestControllerAdvice
public class GeneralExceptionHandler extends ResponseEntityExceptionHandler {

	/**
	 * Handles the RuntimeException and returns a error response with generic response format with error detail.
	 *
	 * @param ex      the RuntimeException that was thrown
	 * @param request the WebRequest during which the exception was thrown
	 * @return a ProblemDetail containing error information
	 */
	@ExceptionHandler(RuntimeException.class)
	public ProblemDetail handleRuntimeException(RuntimeException ex, WebRequest request) {
		return createProblemDetail(
				HttpStatus.BAD_REQUEST,
				"Business Logic Error",
				ex.getMessage(),
				request.getDescription(false).replace("uri=", ""),
				Map.of("error", ex.getMessage())
		);
	}

	/**
	 * Handles the MethodArgumentNotValidException and returns a error response with generic response format with error detail
	 *
	 * @param ex      the MethodArgumentNotValidException that was thrown
	 * @param headers the HttpHeaders during which the exception was thrown
	 * @param status  the HttpStatusCode during which the exception was thrown
	 * @param request the WebRequest during which the exception was thrown
	 * @return a ResponseEntity containing a ProblemDetail with validation error information
	 */
	@Override
	protected ResponseEntity<Object> handleMethodArgumentNotValid(
			MethodArgumentNotValidException ex, HttpHeaders headers, HttpStatusCode status, WebRequest request) {

		var errors = ex.getBindingResult().getFieldErrors()
				.stream()
				.collect(Collectors.toMap(
						FieldError::getField,
						fieldError -> fieldError.getDefaultMessage() != null ? fieldError.getDefaultMessage() : "Invalid value",
						(existing, replacement) -> existing
				));

		ProblemDetail pd = createProblemDetail(
				status,
				"Validation Failed",
				"One or more fields are invalid.",
				request.getDescription(false).replace("uri=", ""),
				errors
		);

		return ResponseEntity.status(status).body(pd);
	}

	/**
	 * The Problem Detail object  - the common error response object format for all the error responses generated by the service.
	 *
	 * @param status  the HTTP status code to be set in the ProblemDetail
	 * @param title   the title of the problem
	 * @param detail  the detailed message describing the problem
	 * @param instance the URI instance where the problem occurred
	 * @param errors  a map containing specific error details, such as field validation errors
	 * @return a ProblemDetail object populated with the provided information
	 */
	private ProblemDetail createProblemDetail(HttpStatusCode status, String title, String detail, String instance, Map<String, String> errors) {
		ProblemDetail problemDetal = ProblemDetail.forStatusAndDetail(status, detail);
		problemDetal.setTitle(title);
		problemDetal.setInstance(URI.create(instance));
		problemDetal.setProperty("timestamp", Instant.now());
		problemDetal.setProperty("errors", errors);
		return problemDetal;
	}
}
